Hospital Filters
Mephiles/torntools_2 pull request #125
Opened 2021-04-27 06:38 UTC by Sashank999

2021-04-27 18:40 UTC, DeKleineKobini requested changes

2021-04-27 18:40 UTC, DeKleineKobini commented on extension/scripts/features/hospitalfilter/ttHospitalFilter.js
> +				if (show) li.classList && li.classList.remove("hidden");
Don't call functions this way.

2021-04-27 18:40 UTC, DeKleineKobini commented on extension/scripts/features/hospitalfilter/ttHospitalFilter.js
> +				else li.classList && li.classList.add("hidden");
Don't call functions this way.

2021-04-27 18:40 UTC, DeKleineKobini commented on extension/scripts/global/functions/slider.js
> +function newSlider() {
This should have a minimum and maximum value, instead of always being 0-100.

2021-04-28 09:40 UTC, Sashank999 commented on extension/scripts/features/hospitalfilter/ttHospitalFilter.css
> +.statistic {
Changed.

2021-04-28 09:40 UTC, Sashank999 commented on extension/scripts/global/functions/filters.css
> +    margin: 1px 5px 0px;
Changed.

2021-04-29 18:42 UTC, DeKleineKobini commented
1. New sliders seem too 'fat' .
2. Text beneath them isn't centered.
3. They take too much space, so the faction combobox doesn't have enough place
    I'm honestly not a fan of setting a margin to a %, as it mostly looks shit on other sizes. Forcing a width to the combobox isn't needed either imo, a max-width at max.

2021-04-29 18:48 UTC, DeKleineKobini requested changes
Comments from above apply.

The sliders aren't centered on mobile as well.

2021-04-29 18:48 UTC, DeKleineKobini commented on extension/scripts/global/functions/filters.css
> +	margin-left: 30%;
I'm honestly not a fan of setting a margin to a %, as it mostly looks shit on other sizes.

2021-04-29 18:48 UTC, DeKleineKobini commented on extension/scripts/global/functions/filters.css
> +	width: 40%;
Forcing a width to the combobox isn't needed either imo, a max-width at max.

2021-04-29 18:48 UTC, DeKleineKobini commented on extension/scripts/features/hospitalfilter/ttHospitalFilter.css
> +	margin-left: 15%;
I'm honestly not a fan of setting a margin to a %, as it mostly looks shit on other sizes.

2021-04-30 08:03 UTC, DeKleineKobini approved these changes

2021-04-30 09:37 UTC, merged