Stock Acronyms
Mephiles/torntools_2 pull request #130
Opened 2021-04-28 12:07 UTC by Sashank999

Closes #50 .

2021-04-29 15:01 UTC, DeKleineKobini requested changes

2021-04-29 15:01 UTC, DeKleineKobini commented on extension/scripts/features/stockacronyms/ttStockAcronyms.js
> +			stockName.find("[class*='nameContainer__']").insertAdjacentElement("afterBegin", document.newElement({
"afterbegin"

2021-04-29 16:04 UTC, Sashank999 commented on extension/scripts/features/stockacronyms/ttStockAcronyms.js
> +			stockName.find("[class*='nameContainer__']").insertAdjacentElement("afterBegin", document.newElement({
Changed.

2021-04-29 19:07 UTC, DeKleineKobini commented
I honestly don't like the position. Will have Mephiles judge it.

![Screenshot](https://i.imgur.com/SgIS5dL.png)

2021-05-01 11:56 UTC, DeKleineKobini approved these changes

2021-05-01 11:56 UTC, merged