Show Nerve Gains beside Alcohols
Mephiles/torntools_2 pull request #133
Opened 2021-04-29 13:23 UTC by Sashank999

Closes #113 .

2021-04-29 19:19 UTC, DeKleineKobini requested changes

2021-04-29 19:19 UTC, DeKleineKobini commented on extension/scripts/features/nervegainsbesidealc/ttNerveGainsBesideAlc.js
> +		CUSTOM_LISTENERS[EVENT_CHANNELS.ITEM_SWITCH_TAB].push(() => {
Same comment as the candy PR.

2021-04-30 04:35 UTC, Sashank999 commented
Done.

2021-04-30 07:59 UTC, DeKleineKobini approved these changes

2021-04-30 09:38 UTC, merged