New abroad people filter && New tools for filters
Mephiles/torntools_2 pull request #329
Opened 2021-07-09 14:35 UTC by Sashank999

Closes #250 .

2021-07-09 14:38 UTC, Sashank999 commented
If the new system is okay, I will also adopt the Abroad Items Filter to this system.

2021-07-09 18:38 UTC, DeKleineKobini requested changes
The filter should not move when the statistic label changes size.

2021-07-10 09:42 UTC, DeKleineKobini requested changes

2021-07-10 09:42 UTC, DeKleineKobini commented on extension/scripts/features/abroad-items-filter/ttAbroadItemsFilter.js
> +	if (getSearchParameters().get("page")) return;
Should be `has`.

2021-07-10 09:48 UTC, Sashank999 commented on extension/scripts/features/abroad-items-filter/ttAbroadItemsFilter.js
> +	if (getSearchParameters().get("page")) return;
Done.

2021-07-10 10:05 UTC, merged