Employee Inactivity Warning
Mephiles/torntools_2 pull request #380
Opened 2021-07-29 10:21 UTC by Sashank999

Closes #226 .

2021-07-29 10:39 UTC, DeKleineKobini requested changes

2021-07-29 10:39 UTC, DeKleineKobini commented on extension/pages/settings/settings.html
> -						<div class="header">Job Specials</div>
This header was specifically chosen to make it more clear what those settings are about. Instead of changing it, you should make a new header.

2021-07-29 10:39 UTC, DeKleineKobini commented on extension/scripts/features/employee-inactivity-warning/ttEmployeeInactivityWarning.js
> +		document.documentElement.style.setProperty("--tt-inactive-one-background-color", Object.entries(settings.employeeInactivityWarning)[0][1]);
No need to expose those properties to the entire document, add them to a relevant element.

2021-07-29 10:39 UTC, DeKleineKobini commented on extension/scripts/features/last-action/ttCompanyLastAction.js
>  				if (getHashParameters().get("option") === "employees") addLastAction(true);
This check is not needed anymore due to the custom listener, right?

2021-07-29 10:39 UTC, DeKleineKobini commented on extension/scripts/features/last-action/ttCompanyLastAction.js
> +		triggerCustomListener(EVENT_CHANNELS.FEATURE_ENABLED, { name: feature.name });
The feature shouldn't send out this event, the feature manager will handle it if you register it properly.

After the `requirements`, you can add an `options` object to registering the feature. Settings `triggerCallback` to true will trigger this listener.

2021-07-29 10:39 UTC, DeKleineKobini commented on extension/scripts/features/last-action/ttCompanyLastAction.js
> +						attributes: {
You shouldn't add data as attributes, use `dataset` for that.

2021-07-29 10:39 UTC, DeKleineKobini commented on extension/scripts/features/employee-inactivity-warning/ttEmployeeInactivityWarning.js
> +			x.classList.remove("tt-modified");
You can remove all of them using 1 call. Just pass them as extra parameters.

2021-07-30 10:19 UTC, Sashank999 reviewed
Done.

2021-07-30 18:08 UTC, DeKleineKobini commented
![Screenshot](https://i.imgur.com/QvnvVjv.png)

When only 1 color is selected, the other one is be used.

2021-07-30 18:16 UTC, merged